SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population_density]
      ,[new_vaccinations]
      ,[RollingPeopleVaccinated]
  FROM [master].[dbo].[PercentPopulationVaccinated]
